### ISSUE TITLE
CEF not accepting power at all from some FE conduits

### ISSUE THREAD

**Issue by RRyyas** [Tictim/CEU#3]
I have a custom modpack that includes GTCE and this mod along with lots of other tech mods so that there is intercompability between the systems. I tried to use Mekanism Universal Cables and they don't seem to work with the CEF regardless of voltage-tier. However when i tried a different type of cable such as the LV cable from Industrial Renewal, then the CEF suddenly works and starts accepting power and converting it into EU

Edit: It also depends on if there's other machines connected to the cables. It either works if you place it right next to the generator source, or if you place a battery in between the cables and the CEF to work as a buffer for it. But still, whether it accepts power or not is quite buggy.

**Comment by Tictim** [comment]
Sounds like Mekanism cables don't care about connected sides. There are two ways of interacting with energy system, the one being sided access and sort of "internal/generic" non-sided access. I specifically blocked off the latter but I guess it made some undesired consequences. I'm kind of short on time right now so I'll work on it later.

It kind of sucks too because if I change it so the machine hands out data to non-sided access, now they are exposed to everywhere. Mods that uses sided access are fine. But with Mechanism cables, it means you would be able to inject FE to CEF and extract FE from CEU, on every side. It wouldn't be game breaking of course. Just another haha funny lil' oddities that bothers me.

**Comment by RRyyas** [comment]
Mekanism cables have a feature where you could push/pull power using a configurator, but even by setting the cable to "push" power into the CEF it still wouldn't work. Maybe thought that the CEF tries to backfeed the stored power but that's not the case. Usually Forge Energy machines have within the API that allow it to only receive power
